import enum

# App exit code
EXIT_CORE_NOT_OPEN_PORT = 10

# TUYA specific constant
TUYA_PACKET_HEADER = b'\x55\xAA'

TUYA_MIN_PACKET_SIZE = 7
TUYA_MAX_PACKET_SIZE = 255
TUYA_MIN_VALUE_SIZE = 5
TUYA_MIN_DATA_STREAM_SIZE = 6
TUYA_MIN_LOCAL_TIME_SIZE = 8

TUYA_RAW_VALUE_TYPE = 0x00
TUYA_BOOLEAN_VALUE_TYPE = 0x01
TUYA_NUMBER_VALUE_TYPE = 0x02
TUYA_STRING_VALUE_TYPE = 0x03
TUYA_ENUM_VALUE_TYPE = 0x04
TUYA_BITMAP_VALUE_TYPE = 0x05
