# App exit code
EXIT_CORE_NOT_OPEN_PORT = 10

# TUYA specific constant
TUYA_PACKET_HEADER = b'\x55\xAA'
TUYA_MIN_PACKET_SIZE = 7
TUYA_MAX_PACKET_SIZE = 255

TUYA_UPDATE_VERSION = 0x00
TUYA_EXTENSION_VERSION = 0x03
